name: Publish
on:
  release:
    types: published

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt'
          cache: 'gradle'

      - name: Publish to Central Repository
        uses: ihub-pub/bot/publish@589999ea8b8b2801650a3596a7477db0399bee09 # v2.0.0
        with:
          repoUsername: ${{ secrets.REPO_USERNAME }}
          repoPassword: ${{ secrets.REPO_PASSWORD }}
          release: true
          parallel: false
          signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          signingSecretKey: ${{ secrets.SIGNING_SECRET_KEY }}
