name: Publish
on:
  release:
    types: published

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt'
          cache: 'gradle'

      - name: Publish to Central Repository
        uses: ihub-pub/bot/publish@d76b43566a1c0ded9fd7db3ffdb623cc6e40d0d9 # v3.0.0
        with:
          repoUsername: ${{ secrets.REPO_USERNAME }}
          repoPassword: ${{ secrets.REPO_PASSWORD }}
          release: true
          parallel: false
          signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          signingSecretKey: ${{ secrets.SIGNING_SECRET_KEY }}
